symbols:
  - CL=F
  - GC=F
  - SPY
  - AMD
  - ^GSPC
  - ^DJI
  - ^IXIC
  - ^RUT
  - ^CASE30
  - ^EGX30CAPPED.CA
  - ^EGX50EWI.CA
  - ^EGX70EWI.CA
  - ^EGX100EWI.CA
  - EGP=X
  - EUREGP=X
  - EGPUSD=X
  - EGPEUR=X
  - EGPMYX=X
  - ^CMC200
  - BTC-USD
  - ETH-USD
  - XMR-USD
  - ZEC-USD
  - SCRT-USD

# Possible values: line, candle, kagi
chart_type: line

# Possible values: 1D, 1W, 1M, 3M, 6M, 1Y, 5Y
time_frame: 1D

# Default is 1
update_interval: 1

# Enable pre / post market hours for graphs
enable_pre_post: true

# Hide help icon in top right
hide_help: true

# Hide previous close line on 1D chart
hide_prev_close: true

# Hide toggle block
hide_toggle: true

# Show volumes graph
show_volumes: true

# Show x-axis labels
show_x_labels: true

# Start in summary mode
summary: true

# Truncate pre market graphing to only 30 minutes prior to markets opening
trunc_pre: true

# reversal can be supplied as a single value, or a map on time frame to give each
# time frame a different reversal amount
# reversal.type can be 'amount' or 'pct'
# price can be 'close' or 'high_low'
kagi_options:
  SPY:
    reversal:
      type: amount
      value: 5.00
    price: close
