#!/bin/sh

# Query
if [[ $* == *-Q* ]]; then
    basename $(cat $HOME/.local/share/backgrounds/wallpaper.png)
    exit
fi

# List
if [[ $* == *-L* ]]; then
    ls -1R ~/Pictures/Wallpapers/ | grep -E ".png|.jpg|.jpeg"
    exit
fi

# Random
if [[ $* == *-R* ]]; then
    wallpaper=$(setwallpaper -L | shuf -n 1)
# Specified
else
    wallpaper=$1
fi

wallpaper=~/Pictures/Wallpapers/"${wallpaper}"

rsync "${wallpaper}" $HOME/.local/share/backgrounds/wallpaper.png

if [[ $(flavours current) == "generated" ]]; then
    flavours generate $(darkmode query) "${wallpaper}" && flavours apply -l generated
fi
