#!/bin/sh

BUKU_DB="$HOME/.local/share/buku/bookmarks.db"
XBELSUM="$HOME/.local/share/buku/XBELSUM"
DBSUM="$HOME/.local/share/buku/DBSUM"

md5sum -c --quiet $XBELSUM
if [ $? -eq 1 ]; then
	$HOME/.local/bin/buku --tacit -i $BUKU_XBEL
	echo "y" | buku --nostdin -e $BUKU_XBEL
	echo "y" | buku --nostdin -e $BUKU_MD
	md5sum $BUKU_XBEL > $XBELSUM
	md5sum $BUKU_DB > $DBSUM
else
	md5sum -c --quiet $DBSUM
	if [ $? -eq 1 ]; then
	echo "y" | buku --nostdin -e $BUKU_XBEL
	echo "y" | buku --nostdin -e $BUKU_MD
	md5sum $BUKU_XBEL > $XBELSUM
	md5sum $BUKU_DB > $DBSUM
	fi
fi
