#!/bin/sh

# Start flavours bemenu
# Base16 Nord
# Author: arcticicestudio

_gen_bemenu_default_opts() {

local color00='#2E3440'
local color01='#3B4252'
local color02='#434C5E'
local color03='#4C566A'
local color04='#D8DEE9'
local color05='#E5E9F0'
local color06='#ECEFF4'
local color07='#8FBCBB'
local color08='#BF616A'
local color09='#D08770'
local color0A='#EBCB8B'
local color0B='#A3BE8C'
local color0C='#88C0D0'
local color0D='#81A1C1'
local color0E='#B48EAD'
local color0F='#5E81AC'

export BEMENU_OPTS="$BEMENU_OPTS"\
"--tb $color03\
 --tf $color06\
 --fb $color00\
 --ff $color06\
 --nb $color00\
 --nf $color04\
 --hb $color02\
 --hf $color0A\
 --sb $color02\
 --sf $color0A\
 --scb $color00\
 --scf $color0E"
}

_gen_bemenu_default_opts
# End flavours bemenu

/usr/bin/pinentry-bemenu -i -H 32
